ptetatau21_reweighting:
  2022_preEE:
    file: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2022_preEE_reweighting.json
    category: pt250msd50mreg50to200bbtag05
    # category: pt300msd80to170
  2022_postEE:
    file: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2022_postEE_reweighting.json
    category: pt250msd50mreg50to200bbtag05
    # category: pt300msd80to170
  2023_preBPix:
    file: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2023_preBPix_reweighting.json
    category: pt250msd50mreg50to200bbtag05
    # category: pt300msd80to170
  2023_postBPix:
    file: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2023_postBPix_reweighting.json
    category: pt250msd50mreg50to200bbtag05
    # category: pt300msd80to170
