ptetatau21_reweighting:
  2022_preEE:
    file: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2022_preEE_reweighting.json
    category: leadpt300msd50subleadpt250msd50mreg50to200
  2022_postEE:
    file: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2022_postEE_reweighting.json
    category: leadpt300msd50subleadpt250msd50mreg50to200
  2023_preBPix:
    file: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2023_preBPix_reweighting.json
    category: leadpt300msd50subleadpt250msd50mreg50to200
  2023_postBPix:
    file: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2023_postBPix_reweighting.json
    category: leadpt300msd50subleadpt250msd50mreg50to200
