scaleout: 50
cores-per-worker: 1
mem-per-worker: "5GB"
disk-per-worker: "1GB"
queue: "standard"
walltime: "12:00:00"
chunksize: 50000
retries: 2
  #tree-reduction: 5
# group-samples:
#   TTto4Q:
#     - "TTto4Q"
#   Vjets:
#     - "VJets"
#   SingleTop:
#     - "SingleTop"
