scaleout: 30
cores-per-worker: 1
mem-per-worker: "17GB"
disk-per-worker: "1GB"
queue: "standard"
walltime: "12:00:00"
chunksize: 50000
retries: 0
  #tree-reduction: 5
group-samples:
  TTto4Q:
    - "TTto4Q"
  Vjets:
    - "VJets"
  SingleTop:
    - "SingleTop"
